version: '3.4'

services:
  seandotnetdocker:
    image: ${DOCKER_REGISTRY}seandotnetdocker
    build:
      context: .
      dockerfile: SeanDotNetDocker/Dockerfile
    restart: always
    depends_on: 
      - seanmysql
    links:
      - seanmysql
    networks: 
      - seannet

  seanmysql:
    container_name: seanmysql
    build:
      context: ./SeanMysql
      dockerfile: Dockerfile
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    networks: 
      - seannet
    volumes:
      - seanvolumes:/var/lib/mysql

networks: 
  seannet:

volumes:
  seanvolumes: